[theme]
base = "light"
primaryColor = "#1D4E47"
backgroundColor = "#F4F1EA"
secondaryBackgroundColor = "#FBFAF7"
textColor = "#16202A"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
